//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocoloNFe.ServiceConsultaNFCe4_0 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", ConfigurationName="ServiceConsultaNFCe4_0.NFeConsultaProtocolo4Soap")]
    public interface NFeConsultaProtocolo4Soap {
        
        // CODEGEN: Generating message contract since the operation nfeConsultaNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFResponse nfeConsultaNF(ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFResponse> nfeConsultaNFAsync(ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeConsultaNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeConsultaNFRequest() {
        }
        
        public nfeConsultaNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeConsultaNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeConsultaNFResponse() {
        }
        
        public nfeConsultaNFResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeConsultaProtocolo4SoapChannel : ProtocoloNFe.ServiceConsultaNFCe4_0.NFeConsultaProtocolo4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeConsultaProtocolo4SoapClient : System.ServiceModel.ClientBase<ProtocoloNFe.ServiceConsultaNFCe4_0.NFeConsultaProtocolo4Soap>, ProtocoloNFe.ServiceConsultaNFCe4_0.NFeConsultaProtocolo4Soap {
        
        public NFeConsultaProtocolo4SoapClient() {
        }
        
        public NFeConsultaProtocolo4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeConsultaProtocolo4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeConsultaProtocolo4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeConsultaProtocolo4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFResponse ProtocoloNFe.ServiceConsultaNFCe4_0.NFeConsultaProtocolo4Soap.nfeConsultaNF(ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFRequest request) {
            return base.Channel.nfeConsultaNF(request);
        }
        
        public System.Xml.XmlNode nfeConsultaNF(System.Xml.XmlNode nfeDadosMsg) {
            ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFRequest inValue = new ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFResponse retVal = ((ProtocoloNFe.ServiceConsultaNFCe4_0.NFeConsultaProtocolo4Soap)(this)).nfeConsultaNF(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFResponse> ProtocoloNFe.ServiceConsultaNFCe4_0.NFeConsultaProtocolo4Soap.nfeConsultaNFAsync(ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFRequest request) {
            return base.Channel.nfeConsultaNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFResponse> nfeConsultaNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFRequest inValue = new ProtocoloNFe.ServiceConsultaNFCe4_0.nfeConsultaNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((ProtocoloNFe.ServiceConsultaNFCe4_0.NFeConsultaProtocolo4Soap)(this)).nfeConsultaNFAsync(inValue);
        }
    }
}
